/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormAddUser: typeof import('./src/components/Forms/FormAddUser.vue')['default']
    FormEditUser: typeof import('./src/components/Forms/FormEditUser.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/User.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
